import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorViewer } from '../Components/ErrorViewer/login'
import { FileUploader } from '../Components/FileUploader/login'
import { Header } from '../Components/header'
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css';
import { ItemSelect, SelectItemIE } from '../Components/ItemSelect/login'
import { useState } from 'react'
import { useRouter } from 'next/router'



const About: NextPage = () => {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <div className={styles.upload} style={{paddingTop:"100px", paddingBottom:"100px"}}>
            <div className={styles.h1} >Наша команда</div>
            <div className={styles.profileWrapper}>
                <img className={styles.profileCard} src="/images/member1.jpg"></img>
            </div>
            <div>
                <div className={styles.mText}>Cсылка на репозиторий GitHub:</div>
                <div className={styles.sourceLink}>https://github.com/Hacks-AI-NJTech/repositories</div>
                <div className={styles.mText}>Cсылка на презентацию:</div>
                <div className={styles.sourceLink}>hhttps://github.com/Hacks-AI-NJTech/repositories</div>
            </div>
        </div>
      </main>
    </div>
  )
}

export default About
